### ISSUE TITLE
install fails on ubuntu

### ISSUE THREAD

**Issue by ralphtheninja** [Level/leveldown-mobile#2]
```
$ npm i leveldown-mobile
-
> leveldown-mobile@1.0.6 install /home/lms/tmp/node_modules/leveldown-mobile
> node-gyp rebuild

gyp: name 'node_engine_mozilla' is not defined while evaluating condition 'node_engine_mozilla!=1' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-39-generic
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lms/tmp/node_modules/leveldown-mobile
gyp ERR! node -v v2.3.1
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Linux 3.16.0-39-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "leveldown-mobile"
npm ERR! node v2.3.1
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! leveldown-mobile@1.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown-mobile@1.0.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lms/tmp/npm-debug.log
```

See more verbose log [here](https://gist.github.com/ralphtheninja/529b8f5aaa26a1653c16)

**Comment by ralphtheninja** [comment]
@obastemur I'm not sure if this should work or not :)

**Comment by obastemur** [comment]
This should work. At least it should skip compiling native parts under npm. I'm going to make some more tests before commit. Thanks!

**Comment by obastemur** [comment]
https://github.com/Level/leveldown-mobile/commit/0c5ebcf03c276723c4c928a87228a63e642cf07c fixes this issue. Thanks

**Comment by ralphtheninja** [comment]
:+1:

**Comment by ralphtheninja** [comment]
Hmm I still get the same error

**Comment by obastemur** [comment]
Strange. I've just updated to latest npm and saw the problem on verbose mode;

> gyp: name 'node_engine_mozilla' is not defined while evaluating condition 'node_engine_mozilla!=1' in binding.gyp while trying to load binding.gyp

This node_engine_mozilla is only used under leveldown_embedded.gyp which has nothing to do with npm. Maybe we should just put that file into npmignore ?

**Comment by obastemur** [comment]
This works without a problem. Maybe I should npmignore leveldown_embedded.gyp for real and re-publish.
```
git clone https://github.com/level/leveldown-mobile
cd leveldown-mobile
npm install
```

Any advice?

**Comment by ralphtheninja** [comment]
@obastemur If `leveldown_embedded.gyp` is not needed for installing with npm it could definitely be added .npmignore

@mcollina @rvagg Anything to add?

**Comment by ralphtheninja** [comment]
cc @juliangruber

**Comment by ralphtheninja** [comment]
@obastemur Oh also, may try to convince you to do `npm version major|minor|patch` when publishing to npm?

**Comment by obastemur** [comment]
@ralphtheninja sure. So far I was only updating the last digit of the version. How should I proceed ? i.e. what version should be when updating to latest leveldown version ?

**Comment by ralphtheninja** [comment]
I'd update minor for that.

**Comment by obastemur** [comment]
Sounds good.

**Comment by obastemur** [comment]
I just confirmed that ignoring additional gyp file fixed the issue on ubuntu. @ralphtheninja Thanks for help.
