### ISSUE TITLE
Uncaught errors with a test app on OS X

### ISSUE THREAD

**Issue by vjrantal** [Level/leveldown-mobile#6]
To reproduce:

* Extract attached [leveldown-mobile-test.zip](https://github.com/Level/leveldown-mobile/files/107951/leveldown-mobile-test.zip)
* Run `jx npm install --no-optional` in the root of the project
  * The `--no-optional` flag is important, because otherwise, pouchdb installs leveldown package which causes the test app to crash
* run `jx index.js`

At least on my environment, the following gets printed:
```
$ jx index.js 
Listening...
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
<unknown>:-1: Uncaught TypeError: Cannot convert null to object
```

```
$ jx -jxv
v0.3.1.0
$ jx -jsv
Google V8 v3.14.5.9
$ jx npm --version
3.3.12
```

**Comment by vjrantal** [comment]
@obastemur: And forgot to mention that such errors are not printed if using `leveldown`. This is mentioned also in the index.js file found from the attached .zip.

**Comment by obastemur** [comment]
@vjrantal Can you please test if latest master fixes this issue? CI is green for master.

**Comment by vjrantal** [comment]
@obastemur: No more errors with the version from `master`. Thanks for taking a look at this and great to see CI green! :+1: :+1:

**Comment by obastemur** [comment]
Great. Published the latest to npm. Thanks for details and quick feedback.
